spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create   # create / create-drop / update / validate / none ? ?1
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      encoding: UTF-8

  h2:
    console:
      enabled: true
      path: /h2-console
